title: muOS
description: Custom Firmware (CFW) primarily for handheld devices. Configurable, themeable, friendly, easy-to-use.
theme: just-the-docs

url: https://muos.dev

color_scheme: muos

aux_links:
  Download: /release/current/pixie
  Discord: https://discord.gg/USS5ybVtDz
  Support: https://ko-fi.com/xonglebongle

callouts:
  warning:
    title: Warning
    color: red
  highlight:
    title: Attention
    color: yellow
  note:
    title: Note
    color: purple
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
